apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80         # Exposed port on the service (accessible externally)
      targetPort: 5000  # Port where the Flask app is running inside the container
  type: NodePort  # This exposes the service externally via Minikube IP
